### ISSUE TITLE
Question - Going from markdown to a custom component?

### ISSUE THREAD

**Issue by babsonmatt** [alexkuz/markdown-react-js#1]
First off, thanks a lot of the library... looks great.  I'm trying to figure out what I would need to do to go all the way from custom mark down syntax, to a React component.

So for example, say I wanted to turn <<blah.mp3>> into a React based audio player component.

I understand there's handleIterate, but by the time handleIterate is called, the markdown is already coming back as HTML.  Would I need to turn <<blah.mp3>> into something like <div class="component-audio" src="blah.mp3" /> and then in handleIterate check based on props for that specific class name?

Thanks in advance,

Matt

**Comment by kof** [comment]
I assume an answer is not needed any more. Sorry for the delay. Please reopen if you still want to discuss.
