### ISSUE TITLE
`convertRules` consider returned HTML-string as strings

### ISSUE THREAD

**Issue by tyv** [alexkuz/markdown-react-js#11]
I am trying to do this https://github.com/markdown-it/markdown-it-emoji#change-output using `markdown-react-js` `convertRules: {emoji: ...}` settings for `mdReact()`.

The problem is: if I return html string it is inserted as string.

~~I was trying to return AST like here https://github.com/alexkuz/markdown-react-js/blob/master/src/index.js#L24 it is more complex, but it works, other problem we have here (and I think it is common and not only my case) is that attrs are not camelCased (e.g. `background-image` and not `backgroundImage` as expected).~~

~~@alexkuz  I've tried somehow to workaround it, but yet no luck, before going deep and spending more time want to ask about maybe any solutions you have in your mind.~~
^^ found correct way to path AST, but still not clear how to return strings

**Comment by kof** [comment]
I am sure this is not relevant any more.
