### ISSUE TITLE
Warning: img dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by shaunthegeek** [alexkuz/markdown-react-js#13]
```
import Markdown from 'markdown-react-js';
<Markdown text={text} />
```

chrome console:

```
Warning: img is a void element tag and must not have `children` or use `props.dangerouslySetInnerHTML`. Check the render method of MDReactComponent.
```

**Comment by dshiells** [comment]
Getting the same issue except with br tags:

> Warning: br is a void element tag and must not have `children` or use `props.dangerouslySetInnerHTML`. Check the render method of MDReactComponent.

Did you find a solution to this @sinkcup?

**Comment by kof** [comment]
This pr is fixing it, https://github.com/alexkuz/markdown-react-js/pull/10/files I got publish rights, will soon merge the prs and release a new version. Need to get tests running though first. Didn't work out at first try.

**Comment by kof** [comment]
fixed
