### ISSUE TITLE
"use strict"

### ISSUE THREAD

**Issue by chpio** [alexkuz/markdown-react-js#2]
hi,

`"use strict"` is not required with es6-modules/babeljs
https://people.mozilla.org/~jorendorff/es6-draft.html#sec-strict-mode-code

> Module code is always strict mode code.

https://github.com/alexkuz/markdown-react-js/blob/master/src/index.js#L1

**Comment by alexkuz** [comment]
True, thanks! :)

Don't hesitate to send PR for this kind of things, BTW.

**Comment by chpio** [comment]
> Don't hesitate to send PR for this kind of things, BTW.

nah, it's not that important :)
Just wanted to say something, so you can fix it in the future when doing something in the code
