### ISSUE TITLE
Can't import lib

### ISSUE THREAD

**Issue by luisrudge** [alexkuz/markdown-react-js#4]
When I import this to my code, I get all this errors:

![image](https://cloud.githubusercontent.com/assets/941075/11289370/445c54cc-8f13-11e5-9aff-201bf7425135.png)

**Comment by luisrudge** [comment]
hey @alexkuz any thoughts on this?

**Comment by alexkuz** [comment]
Just install `babel-runtime` package (it should be in peer dependencies I guess)

**Comment by luisrudge** [comment]
It's not.. it's in devDependencies.. If this is required for the lib to run, it should be a dependency, right?

**Comment by luisrudge** [comment]
I'm having another error:

```
ERROR in ./~/entities/maps/entities.json
Module parse failed: c:\git\project\node_modules\entities\maps\entities.json Line 1: Unexpected token :
You may need an appropriate loader to handle this file type.
```

**Comment by alexkuz** [comment]
You need to use `json-loader`, I guess. Doesn't seem to be related to this project though.

**Comment by luisrudge** [comment]
Yeha.. This is a problem with markdown-it itself.. Sorry :)

**Comment by jeffj** [comment]
Is there a solution for this on an issue in the  markdown-it repository?  I am unable to use the markdown-react-js library because of this bug.
