### ISSUE TITLE
Need some way to pass additional props to onInterate fn 

### ISSUE THREAD

**Issue by kof** [alexkuz/markdown-react-js#9]
Currently mdReact function it is only accepting:

```
  const { onIterate, tags=DEFAULT_TAGS,
    presetName, markdownOptions,
    enableRules=[], disableRules=[], plugins=[],
    onGenerateKey=(tag, index) => `mdrct-${tag}-${index}`,
    className } = options;
```

I think we could take the rest options and merge them with props object we pass to onIterate.

Are you ok with a pr?

**Comment by alexkuz** [comment]
Thanks for PR!
I'm not sure though it's that useful - isn't it easier just to bind these options to `onIterate` handler? Maybe some example?

**Comment by kof** [comment]
This is exactly the problem when you have a non-static data. For e.g. an object that comes from redux and might changes any time, I need to pass that object over props, not statically binding it. Y know what I mean?

**Comment by alexkuz** [comment]
What I mean is:

``` jsx
render() {
  return <Markdown onIterate={handleIterate.bind(this, this.props.myProps)} />
}
```

or, if you don't want to rebind on each render:

``` jsx
render() {
  return <Markdown onIterate={this.handleIterate} />
}

handleIterate = (...) => {
  const { myProps } = this.props;
}
```

sure, if we pass these props to component, there would be a bit shorter code, but it still feels redudant. It would make sense for me though if we pass them only to root component, just like `className`.

**Comment by kof** [comment]
Ah, forgot to tell that I am not using the component, but the mdReact function directly, because component is doing `mdReactFactory(props)(text)` on every render which produces some overhead. I have the `const render = mdReactFactory(props)` cached so I only call `render(text)`.

Maybe you have  a different suggestion how to avoid the overhead of calling mdReactFactory on every render?

**Comment by kof** [comment]
As a next step we could introduce some caching of mdReactFactory result to remove that overhead.

**Comment by kof** [comment]
The reason I am caching mdReactFactory is because of my high performance use case, it parses markdown very frequently and I am trying to reduce everything I can.

**Comment by alexkuz** [comment]
I agree, it's quite inefficient and should be rewritten.
But still, I think something like this should work:

``` jsx
class MyComponent extends Component {
  constructor(props) {
    super(props);
    this.mdReact = mdReactFactory({ ...this.props, onIterate: this.handleIterate });
  }

  render() {
    return this.mdReact(text);
  }

  handleIterate = (...) => {
    const { myProp } = this.props;
    ...
  }
}
```

**Comment by kof** [comment]
You are right, I managed to optimize it like you described.

**Comment by kof** [comment]
Now came to further optimizations, turns out mdReactFactory() call takes 3-7ms, in my case this happens too frequently. I need this function to be called just once.

**Comment by kof** [comment]
Which means that I can't cache it inside of the instance, it needs to be global.

**Comment by kof** [comment]
The only way I see here I see: [this](https://github.com/alexkuz/markdown-react-js/blob/master/src/index.js#L166) function needs to accept additional options, one of each should be onIterate callback.
